---
AWSTemplateFormatVersion: 2010-09-09
Description: This template is used for setting up Security Groups. (qs-1t9ums4k9)
Metadata:
  QSLint:
    Exclusions: [ W9002, W9003, W9004, W9006 ]
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - AccessCIDR
          - VPCID
          - VPCCIDR
          - BastionSecurityGroupID
    ParameterLabels:
      AccessCIDR:
        default: Access CIDR
      VPCID:
        default: VPC ID
      VPCCIDR:
        default: VPC CIDR
      BastionSecurityGroupID:
        default: Bastion security group ID
Parameters:
  AccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in the form x.x.x.x/x.
    Description: "CIDR IP range permitted for access. A value of
      0.0.0.0/0 allows access from any IP address."
    Type: String
  VPCID:
    Description:
      VPC ID of your existing Virtual Private Cloud (VPC) where you want to deploy NebulaGraph.
    Type: AWS::EC2::VPC::Id
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in the form x.x.x.x/x.
    Description: The CIDR block for VPC.
    Type: String
  BastionSecurityGroupID:
    Description: The BastionSecurityGroupID range that is permitted to access.
    Type: String
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to NebulaGraph port.
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 7002
          ToPort: 7002
          CidrIp: !Ref AccessCIDR
        - IpProtocol: tcp
          FromPort: 7005
          ToPort: 7005
          CidrIp: !Ref AccessCIDR
        - IpProtocol: -1
          CidrIp: !Ref VPCCIDR
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref BastionSecurityGroupID
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroupID
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupID:
    Description: NebulaGraph Security Group
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroup"
